// <auto-generated />
using System;
using Botticelli.Broadcasting.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Botticelli.Broadcasting.Dal.Migrations
{
    [DbContext(typeof(BroadcastingContext))]
    [Migration("20250603202442_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("Botticelli.Broadcasting.Dal.Models.Chat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Botticelli.Broadcasting.Dal.Models.MessageCache", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerializedMessageObject")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MessageCaches");
                });

            modelBuilder.Entity("Botticelli.Broadcasting.Dal.Models.MessageStatus", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "MessageId");

                    b.ToTable("MessageStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
