<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Botticelli.Framework.Chained.Context\Botticelli.Framework.Chained.Context.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="StackExchange.Redis" Version="2.8.37" />
      <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    </ItemGroup>

</Project>
