// <auto-generated />
using Botticelli.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Botticelli.Bot.Data.Migrations
{
    [DbContext(typeof(BotInfoContext))]
    [Migration("20241021193257_botdata")]
    partial class botdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Botticelli.Bot.Data.Entities.Bot.BotAdditionalInfo", b =>
                {
                    b.Property<string>("BotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BotDataBotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemValue")
                        .HasColumnType("TEXT");

                    b.HasKey("BotId");

                    b.HasIndex("BotDataBotId");

                    b.ToTable("BotAdditionalInfos");
                });

            modelBuilder.Entity("Botticelli.Bot.Data.Entities.Bot.BotData", b =>
                {
                    b.Property<string>("BotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BotKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("BotId");

                    b.ToTable("BotData");
                });

            modelBuilder.Entity("Botticelli.Bot.Data.Entities.Bot.BotAdditionalInfo", b =>
                {
                    b.HasOne("Botticelli.Bot.Data.Entities.Bot.BotData", null)
                        .WithMany("AdditionalInfo")
                        .HasForeignKey("BotDataBotId");
                });

            modelBuilder.Entity("Botticelli.Bot.Data.Entities.Bot.BotData", b =>
                {
                    b.Navigation("AdditionalInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
