<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>0.8.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Botticelli.Framework\Botticelli.Framework.csproj" />
    </ItemGroup>

</Project>
