// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Botticelli.Auth.Data.Postgres.Migrations
{
    [DbContext(typeof(AuthDefaultDbContext))]
    partial class AuthDefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Botticelli.Auth.Sample.Telegram")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Botticelli.Auth.Sample.Telegram.Dal.AccessHistory<Botticelli.Auth.Sample.Telegram.Dal.Models.BotUser>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntityUserId")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityUserId");

                    b.ToTable("AccessHistory", "Botticelli.Auth.Sample.Telegram");
                });

            modelBuilder.Entity("Botticelli.Auth.Sample.Telegram.Dal.Models.BotUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NickName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("BotUsers", "Botticelli.Auth.Sample.Telegram");
                });

            modelBuilder.Entity("Botticelli.Auth.Sample.Telegram.Dal.Models.BotUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("BotUserRoles", "Botticelli.Auth.Sample.Telegram");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9887829-61a7-4947-9eb6-7faa66363f08"),
                            Description = "Bot users administrator",
                            IsSuperUser = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("9947e363-4255-408d-b277-33402b9f07a1"),
                            Description = "A default user for guest",
                            IsSuperUser = false,
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("Botticelli.Auth.Sample.Telegram.Dal.AccessHistory<Botticelli.Auth.Sample.Telegram.Dal.Models.BotUser>", b =>
                {
                    b.HasOne("Botticelli.Auth.Sample.Telegram.Dal.Models.BotUser", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityUserId");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Botticelli.Auth.Sample.Telegram.Dal.Models.BotUser", b =>
                {
                    b.HasOne("Botticelli.Auth.Sample.Telegram.Dal.Models.BotUserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
