<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>

		<IsPackable>false</IsPackable>

		<RootNamespace>Botticelli.AI.TEST</RootNamespace>

		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.2.0"/>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
		<PackageReference Include="NUnit" Version="4.3.2"/>
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/>
		<PackageReference Include="System.Text.Json" Version="8.0.5"/>
		<PackageReference Include="WireMock.Net" Version="1.6.7"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Botticelli.AI.ChatGpt\Botticelli.AI.ChatGpt.csproj"/>
		<ProjectReference Include="..\Botticelli.AI.DeepSeekGpt\Botticelli.AI.DeepSeekGpt.csproj"/>
		<ProjectReference Include="..\Botticelli.AI.YaGpt\Botticelli.AI.YaGpt.csproj"/>
		<ProjectReference Include="..\Botticelli.AI\Botticelli.AI.csproj"/>
		<ProjectReference Include="..\Tests\Mocks\Mocks.csproj" />
	</ItemGroup>

</Project>